### PR TITLE
Add VlbgWebDev to Meetup section

### PR DESCRIPTION
**Pull request by danrot**

### CODE REVIEW

**Comment by mxstbr** [comment]
Zt zt zt Daniel, can't even follow contribution guidelines. 🙄 😉

Can you update the PR body with the comment mentioned in the contribution guidelines and force push again? Thanks!

**Comment by danrot** [comment]
Just read about it, this sentence was a bit hidden, I started after the table of contents, assuming that the rest is just some contentless text 😄

**Review by mxstbr — CHANGES_REQUESTED** [review]
We'll also need to add that to the ToC at the top of the README so people can find it 😊

**Comment by danrot** [comment]
Slowly it's getting awkward 😊

**Review by mxstbr — APPROVED** [review]

**Comment by mxstbr** [comment]
Awesome, thanks!

**Pull request merged**
