### PR TITLE
add Node.js Vienna

### PR DESCRIPTION
**Pull request by nicokaiser**

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]
Awesome, thanks!

**Comment by mxstbr** [comment]
Well, that's an annoying GitHub bug!

screen shot 2017-01-31 at 09 55 31

**Comment by nicokaiser** [comment]
Is there something I can do about this? Or is this just a GitHub bug that prevents it from being merged? (The checks have passed, right?)

**Comment by mxstbr** [comment]
> Is there something I can do about this? Or is this just a GitHub bug that prevents it from being merged?

Looks like a GitHub bug. Can you try force pushing your changes again? Maybe that'll help...

**Comment by mxstbr** [comment]
There we go 🙌 thanks so much!

**Pull request merged**
