### PR TITLE
Adding Technologieplauscherl meetup to the list

### PR DESCRIPTION
**Pull request by bullshit**
I promise I have read the [contribution guidelines](https://github.com/mxstbr/awesome-austria/blob/master/contributing.md) twice and ensured my submission follows it.

Adding Technologieplauscherl meetup to the list

### CODE REVIEW

**Comment by bullshit** [comment]
WTF? Are you serious?

**Comment by mxstbr** [comment]
😉 

Love that GitHub handle btw

**Comment by bullshit** [comment]
A little too exaggerated ;) because i don't know whats the problem

**Comment by mxstbr** [comment]
Just need to force push now to restart the bot, it runs on CI!

**Comment by mxstbr** [comment]
Just to note: what happened was that you initially deleted the `<!-- Leave this text in and start your description of the change below -->` comment, which the bot detected and thusly assumed you didn't read the contribution guidelines.

That's just to make it easier on me when a lot of PRs come in, as I automatically know if people have read them or not and to avoid common issues :blush:

**Comment by bullshit** [comment]
I read it, and successfully delete it :P

**Comment by mxstbr** [comment]
Added via #20, thanks for the PR!

**Pull request closed without merging**
